### ISSUE TITLE
Please Add me!!! - Greetings from Kansas City

### ISSUE THREAD

**Issue by LUXEDinc** [KaOS-Community-Packages/KaOS-Community-Packages.github.io#5]
New to the the real sid of coding. Looking to connect with the coding community!

**Comment by fjmorazan** [comment]
Hi @robertanthonyra!
You can [apply for membership](https://kaosx.us/docs/kcp/#applying-for-membership) and get access to KCP repo so you can edit, update or add your own packages. Make sure you read beforehand https://kaosx.us/docs/kcp/#submitting-a-package, https://kaosx.us/docs/kcp/#formatting-standards-for-kcp and https://kaosx.us/docs/package/

**Comment by ShalokShalom** [comment]
Can this be closed?
